// Code generated by MockGen. DO NOT EDIT.
// Source: persistence/order_repository.go
//
// Generated by this command:
//
//	mockgen -source=persistence/order_repository.go -destination=test/mock/repository/order_repository.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	domain "go-ecommerce-service/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIOrderRepository is a mock of IOrderRepository interface.
type MockIOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockIOrderRepositoryMockRecorder is the mock recorder for MockIOrderRepository.
type MockIOrderRepositoryMockRecorder struct {
	mock *MockIOrderRepository
}

// NewMockIOrderRepository creates a new mock instance.
func NewMockIOrderRepository(ctrl *gomock.Controller) *MockIOrderRepository {
	mock := &MockIOrderRepository{ctrl: ctrl}
	mock.recorder = &MockIOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOrderRepository) EXPECT() *MockIOrderRepositoryMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockIOrderRepository) CreateOrder(order domain.Order) (domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", order)
	ret0, _ := ret[0].(domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockIOrderRepositoryMockRecorder) CreateOrder(order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockIOrderRepository)(nil).CreateOrder), order)
}

// DeleteOrderById mocks base method.
func (m *MockIOrderRepository) DeleteOrderById(orderId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderById", orderId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrderById indicates an expected call of DeleteOrderById.
func (mr *MockIOrderRepositoryMockRecorder) DeleteOrderById(orderId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderById", reflect.TypeOf((*MockIOrderRepository)(nil).DeleteOrderById), orderId)
}

// GetAllOrders mocks base method.
func (m *MockIOrderRepository) GetAllOrders() ([]domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOrders")
	ret0, _ := ret[0].([]domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOrders indicates an expected call of GetAllOrders.
func (mr *MockIOrderRepositoryMockRecorder) GetAllOrders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOrders", reflect.TypeOf((*MockIOrderRepository)(nil).GetAllOrders))
}

// GetOrderById mocks base method.
func (m *MockIOrderRepository) GetOrderById(orderId int64) domain.Order {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderById", orderId)
	ret0, _ := ret[0].(domain.Order)
	return ret0
}

// GetOrderById indicates an expected call of GetOrderById.
func (mr *MockIOrderRepositoryMockRecorder) GetOrderById(orderId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderById", reflect.TypeOf((*MockIOrderRepository)(nil).GetOrderById), orderId)
}

// GetOrdersByStatus mocks base method.
func (m *MockIOrderRepository) GetOrdersByStatus(status string) ([]domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByStatus", status)
	ret0, _ := ret[0].([]domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByStatus indicates an expected call of GetOrdersByStatus.
func (mr *MockIOrderRepositoryMockRecorder) GetOrdersByStatus(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByStatus", reflect.TypeOf((*MockIOrderRepository)(nil).GetOrdersByStatus), status)
}

// GetOrdersByUserId mocks base method.
func (m *MockIOrderRepository) GetOrdersByUserId(userId int64) ([]domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByUserId", userId)
	ret0, _ := ret[0].([]domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByUserId indicates an expected call of GetOrdersByUserId.
func (mr *MockIOrderRepositoryMockRecorder) GetOrdersByUserId(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByUserId", reflect.TypeOf((*MockIOrderRepository)(nil).GetOrdersByUserId), userId)
}

// UpdateOrderStatus mocks base method.
func (m *MockIOrderRepository) UpdateOrderStatus(orderId int64, status string) (domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", orderId, status)
	ret0, _ := ret[0].(domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockIOrderRepositoryMockRecorder) UpdateOrderStatus(orderId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockIOrderRepository)(nil).UpdateOrderStatus), orderId, status)
}

// UpdateOrderTotalPrice mocks base method.
func (m *MockIOrderRepository) UpdateOrderTotalPrice(orderId int64, newTotalPrice float32) (domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderTotalPrice", orderId, newTotalPrice)
	ret0, _ := ret[0].(domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderTotalPrice indicates an expected call of UpdateOrderTotalPrice.
func (mr *MockIOrderRepositoryMockRecorder) UpdateOrderTotalPrice(orderId, newTotalPrice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderTotalPrice", reflect.TypeOf((*MockIOrderRepository)(nil).UpdateOrderTotalPrice), orderId, newTotalPrice)
}
