// Code generated by MockGen. DO NOT EDIT.
// Source: persistence\product_repository.go
//
// Generated by this command:
//
//	mockgen -source=persistence\product_repository.go -destination=test\mock\repository\product_repository.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package repository

import (
	domain "go-ecommerce-service/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIProductRepository is a mock of IProductRepository interface.
type MockIProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIProductRepositoryMockRecorder
	isgomock struct{}
}

// MockIProductRepositoryMockRecorder is the mock recorder for MockIProductRepository.
type MockIProductRepositoryMockRecorder struct {
	mock *MockIProductRepository
}

// NewMockIProductRepository creates a new mock instance.
func NewMockIProductRepository(ctrl *gomock.Controller) *MockIProductRepository {
	mock := &MockIProductRepository{ctrl: ctrl}
	mock.recorder = &MockIProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProductRepository) EXPECT() *MockIProductRepositoryMockRecorder {
	return m.recorder
}

// AddProduct mocks base method.
func (m *MockIProductRepository) AddProduct(product domain.Product) (domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProduct", product)
	ret0, _ := ret[0].(domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProduct indicates an expected call of AddProduct.
func (mr *MockIProductRepositoryMockRecorder) AddProduct(product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProduct", reflect.TypeOf((*MockIProductRepository)(nil).AddProduct), product)
}

// DeleteProductById mocks base method.
func (m *MockIProductRepository) DeleteProductById(productId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductById", productId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProductById indicates an expected call of DeleteProductById.
func (mr *MockIProductRepositoryMockRecorder) DeleteProductById(productId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductById", reflect.TypeOf((*MockIProductRepository)(nil).DeleteProductById), productId)
}

// GetAllProducts mocks base method.
func (m *MockIProductRepository) GetAllProducts() []domain.Product {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProducts")
	ret0, _ := ret[0].([]domain.Product)
	return ret0
}

// GetAllProducts indicates an expected call of GetAllProducts.
func (mr *MockIProductRepositoryMockRecorder) GetAllProducts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProducts", reflect.TypeOf((*MockIProductRepository)(nil).GetAllProducts))
}

// GetProductById mocks base method.
func (m *MockIProductRepository) GetProductById(productId int64) (domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductById", productId)
	ret0, _ := ret[0].(domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductById indicates an expected call of GetProductById.
func (mr *MockIProductRepositoryMockRecorder) GetProductById(productId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductById", reflect.TypeOf((*MockIProductRepository)(nil).GetProductById), productId)
}

// IndexProduct mocks base method.
func (m *MockIProductRepository) IndexProduct(product domain.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexProduct", product)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexProduct indicates an expected call of IndexProduct.
func (mr *MockIProductRepositoryMockRecorder) IndexProduct(product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexProduct", reflect.TypeOf((*MockIProductRepository)(nil).IndexProduct), product)
}

// SearchProducts mocks base method.
func (m *MockIProductRepository) SearchProducts(query string) ([]domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchProducts", query)
	ret0, _ := ret[0].([]domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchProducts indicates an expected call of SearchProducts.
func (mr *MockIProductRepositoryMockRecorder) SearchProducts(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchProducts", reflect.TypeOf((*MockIProductRepository)(nil).SearchProducts), query)
}

// UpdateProduct mocks base method.
func (m *MockIProductRepository) UpdateProduct(productId uint, product domain.Product) (domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", productId, product)
	ret0, _ := ret[0].(domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockIProductRepositoryMockRecorder) UpdateProduct(productId, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockIProductRepository)(nil).UpdateProduct), productId, product)
}
