// Code generated by MockGen. DO NOT EDIT.
// Source: infrastructure/rabbitmq/client.go
//
// Generated by this command:
//
//	mockgen -source=infrastructure/rabbitmq/client.go -destination=test/mock/infrastructure/rabbitmq_mock.go -package=mock_infra
//

// Package mock_infra is a generated GoMock package.
package mock_infra

import (
	reflect "reflect"

	amqp091 "github.com/rabbitmq/amqp091-go"
	gomock "go.uber.org/mock/gomock"
)

// MockIRabbitMQClient is a mock of IRabbitMQClient interface.
type MockIRabbitMQClient struct {
	ctrl     *gomock.Controller
	recorder *MockIRabbitMQClientMockRecorder
	isgomock struct{}
}

// MockIRabbitMQClientMockRecorder is the mock recorder for MockIRabbitMQClient.
type MockIRabbitMQClientMockRecorder struct {
	mock *MockIRabbitMQClient
}

// NewMockIRabbitMQClient creates a new mock instance.
func NewMockIRabbitMQClient(ctrl *gomock.Controller) *MockIRabbitMQClient {
	mock := &MockIRabbitMQClient{ctrl: ctrl}
	mock.recorder = &MockIRabbitMQClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRabbitMQClient) EXPECT() *MockIRabbitMQClientMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockIRabbitMQClient) Publish(exchange, routingKey string, mandatory, immediate bool, msg amqp091.Publishing) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", exchange, routingKey, mandatory, immediate, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockIRabbitMQClientMockRecorder) Publish(exchange, routingKey, mandatory, immediate, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockIRabbitMQClient)(nil).Publish), exchange, routingKey, mandatory, immediate, msg)
}
